### ISSUE TITLE
[Vote ended on 2022-08-03] Disconnect between Docs and Ansible-lint in regards to truthy statements (booleans)

### ISSUE THREAD

**Issue by p-rintz** [ansible-community/community-topics#116]
Hi everyone,

I had brought this up on Matrix and was asked to create an issue here after some discussion.

### Summary

Currently, the Ansible Docs will always use yes/no for truthy statements.
However, Ansible-Lint will throw an error if yes/no is used and will enforce the use of true/false.

`yaml: truthy value should be one of [false, true] (yaml[truthy])`

This is rather inconsistent and (at least on my part) leads to confusion. 

In a discussion on Matrix it was found that Ansible Docs & Automation Hub both enforce the use of yes/no use for truthy statements via an override.

Related issues (where this issue was also brought up, but wasnt followed up on):
https://github.com/ansible/ansible/pull/77581
https://github.com/ansible/ansible-lint/pull/1954

**Comment by felixfontein** [comment]
We had a short discussion on this on June 24th, 2021. In there, some links were burried out:
- The PR in ansible/ansible which changed docs to yes/no: https://github.com/ansible/ansible/pull/36901 (@sivel said during that IRC discussion that the reasoning for `yes`/`no`, as he remembers, is that `true`/`false` is more familiar with programmers, but feels awkward for non-programmers)
- #ansible-docs meeting which allowed both `yes`/`no` and `true`/`false` in documentation: https://meetbot.fedoraproject.org/ansible-docs/2019-01-08/docs_working_group.2019-01-08-15.31.html
- #ansible-docs meeting where boolean standardization was discussed: https://meetbot.fedoraproject.org/ansible-docs/2020-07-14/docs_working_group_aka_dawgs.2020-07-14-14.31.html

The last meeting ended with an action "create a proposal for creating consistency in the boolean values", which I think didn't happen.

**Comment by gundalow** [comment]
Thanks for raising this. I know the current situation is confusing.

I've asked @cidrblock to take a look at this, he's one of the Ansible Architects, and responsible for ansible-lint. He's on holiday though and should be back next week.

**Comment by samccann** [comment]
Regardless of ansible-lint, we should decide again whether that 'user-friendly' override to yes/no is actually user-friendly.  
PRs that seem to have set this docs default:
https://github.com/ansible/ansible/pull/37488
https://github.com/ansible/ansible/pull/42361

We also failed to update text/examples beyond the boolean. Here is an example where the text talks about `true` but the docs override has the parameter using `yes/no`
![image](https://user-images.githubusercontent.com/30267855/176205926-a3614839-0e21-4435-99ae-b1526304512d.png)

**Comment by samccann** [comment]
Another older PR closed that proposed true/false consistency - https://github.com/ansible/ansible/issues/49072

**Comment by felixfontein** [comment]
I personally prefer `true`/`false` over `yes`/`no`. Especially since they are YAML 1.2 booleans, while `yes`/`no` are not. (Which seems to be the main reason why ansible-lint seems to prefer `true`/`false`.)

> We also failed to update text/examples beyond the boolean. Here is an example where the text talks about `true` but the docs override has the parameter using `yes/no` ![image](https://user-images.githubusercontent.com/30267855/176205926-a3614839-0e21-4435-99ae-b1526304512d.png)

Actually that option was added after the `yes`/`no` default was decided. We did talk about this multiple times, and at some time we also said that both `true`/`false` and `yes`/`no` are OK in docs. I wrote that description back then in this way because I preferred (and still prefer) `true`/`false`.

**Comment by samccann** [comment]
It was agreed in the DaWGs (Docs working group) meeting to back out the docs override that is forcing all boolean parameters to say `yes/no` in the docsite.

**Comment by sivel** [comment]
Of note here, and not that it couldn't change, but the core team had discussed that if we started supporting YAML 1.2, we would likely add support back in for 1.1 booleans.

Also one reason that lint has problems is that it's using `ruamel.yaml` for various reasons including rewriting YAML into a consistent format, but that library only has a 1.2 emitter.  This however can be resolved in `ruamel.yaml` by setting `yaml.boolean_representation = ['no', 'yes']`

**Comment by cidrblock** [comment]
I'm inclined to suggest we consistently use true/false while continuing to support the older yaml 1.1 variants in ansible/ansible.

Some reasons include:

- The yaml 1.2 specification is limited to true/false
- Alignment with both JSON and python which use true/false
- I suspect nearly all of the far side systems ansible interacts with use true/false
- Fewer surprises when using yaml libraries across multiple languages

WRT ansible-lint, taken from the docs "The goal of ansible-lint is to ensure the content created by different people has a similar look and feel. This makes the adoption and use of Ansible content easier in the community and enterprise. By keeping the number of configurable features at a minimum, consistent outcomes between authors can be achieved." https://ansible-lint.readthedocs.io/en/latest/philosophy/

This is the main reason why ansible-lint typically suggests one way to do something but still allows for customization by enabling/disabling rules so an organization can make and adhere to a custom rule set.

I'm going to guess it will be a long time before ansible/ansible would drop support for the YAML 1.1 variants but since we can't influence the entire eco-system of tools and systems ansible interacts with, true/false reflecting the YAML 1.2 specification seems to be the best path forward to maintain consistency.

**Comment by mariolenz** [comment]
@cidrblock I think you have some strong arguments there for using `true`/`false`.

Considering your last argument (Fewer surprises when using yaml libraries across multiple languages) I would contest that `yes`/`no` is actually user-friendly. It is _not_ for people using ansible and also other tools that follow the usual `true`/`false` standard for booleans.

**Comment by bcoca** [comment]
Python uses `True/False`, not `true/false`, so you only align with JSON .. which is the least relevant format for Ansible input validation and conversions. 

YAML 1.2 also requires a pragma at the start of any document, since most playbooks don't have it they should be interpreted as 1.1 in any case.

**Comment by bcoca** [comment]
Except Python also takes as false `'', [ ], 0, {}, None` and truth can be 'any string' or non 0 number, any container type with elements, etc.  Not really a road to go down as each component has it's own set, what Ansible does internally is try to normalize them, using the YAML 1.1 as the basis.

**Comment by mariolenz** [comment]
> Except Python also takes as false `'', [ ], 0, {}, None` and truth can be 'any string' or non 0 number, any container type with elements, etc.

And how exactly is this a reason to use `yes` and `no`? With the same argument, you could also justify using `foo` and `bar`...

> what Ansible does internally is try to normalize them, using the YAML 1.1 as the basis.

Whatever Ansible does internally, it accepts `true` and `false` afaik. So I don't think this is an argument against consistently using `true` / `false` in the documentation.

**Comment by samccann** [comment]
From the documentation perspective, we are leaning toward `true/false` instead of the current `yes/no` interpretation for booleans.

**Comment by samccann** [comment]
Adding...it wasn't an override from docs as i thought - documentation has to decide what to put in the output for boolean, so we chose yes/no back in 2018.

**Comment by felixfontein** [comment]
I think we should have a vote on this, with options maybe being a) `true`/`false`, b) `yes`/`no`, c) `True`/`False`, d) let every program handle output as it wants. Right now we basically have d), where docs.ansible.com uses b), ansible-doc uses c), and ansible-lint uses a).

**Comment by mariolenz** [comment]
@bcoca 

> I'm not advocating for either, just pointing out the holes in your argument.

I don't see a hole in the argument. Just because Python (and many other languages) evaluate a lot of things to True or False, if people want to _express_ a Boolean, that is a yes/no value, they usually use True or False. At least in the scripting and programming languages that I know. Even SQL uses TRUE and FALSE. And I think PowerShell uses `$true` and `$false`, but it's still more or less the same.

In GUIs, you often find yes and no. But in text-based tools, I mainly know true and false... well, with differences in uppercase / lowercase and, in PowerShell, an added $ in front.

> IMHO documentation should favor 'the accepted way' of doing things, but should not exclude the other ways since that will then cause users to be surprised and commit errors when encountering other forms (for example the YAML Norway ISO issue ...).

For me, 'the accepted way' to express Boolean values is true and false. Of course, it should be documented that `yes` and `no` are valid alternatives.

Btw: I've never heard of the YAML Norway ISO issue, but it sounds interesting. I'll try to find the time and look it up. Thanks!

> In this case `yes/no` was voted on as being more user friendly and understandable, the main reason against it is 'how ruamel does it', which is used by `ansible-lint`. I"m not against changing the default display, I'm just against using invalid reasons to arrive to the conclusion.

Apart from my personal opinion: The more people using ansible-lint, the more 'the accepted way' might move into the direction of using `true` and `false`. If only to shut up ansible-lint ;-P

**Comment by bcoca** [comment]
Your point was building on cidr's that true/false normalized to Python standards , only reason i went down this rabbit hole.

the norway issue: 
```
myisocode: no 
```
no is the ISO for Norway, YAML instead returns a boolean false unless you `!!str` the variable (Norway went as far as getting new alternative ISO code).

**Comment by felixfontein** [comment]
Suggestion for a vote formulation: https://gist.github.com/felixfontein/9e532485a081266e6e98d9f0469583d2 I will likely create a vote after today's meeting, so if you want something changed, please comment there until then :)

**Comment by mariolenz** [comment]
> Your point was building on cidr's that true/false normalized to Python standards , only reason i went down this rabbit hole.

Sorry, maybe I've expressed myself poorly. I _don't_ want to normalize to Python standards. I just wanted to say that `true` / `false` (no matter if lowercase, Upercase or ALLUPPERCASE) is more common than `yes`/`no`. I see Python just as an example for this.

**Comment by felixfontein** [comment]
I created a vote on this in https://github.com/ansible-community/community-topics/discussions/120. **Please vote there**. If you want to discuss something, please do it here though :)

**Comment by felixfontein** [comment]
@gundalow @thaumos since the current vote count for the steering committee is rather tight (6 votes or 1, 4 votes for 2), I think it would be good if you would also vote in https://github.com/ansible-community/community-topics/discussions/120 (assuming you have an opinion on this :) ).

**Comment by Andersson007** [comment]
My count of votes is:

Community:
- option 1: 15
- option 2: 1
- option 3: 1

SC:
- option 1: 7
- option 2: 4

So **option 1** `true` `false` is a clear winner.

**Comment by felixfontein** [comment]
I counted votes:
- Steering Committee: 6 x 1, 4 x 2 as first choice
- Community: 16 x 1, 1 x 2, 1 x 3 as first choice; 2 invalid

<details>
<summary>Raw vote data:</summary>

felixfontein,1,2,4,3
briantist,1,2,4,3
ssbarnea,1,1,1,1
russoz,1,1,1,1
cidrblock,1,1,1,1
mariolenz,1,1,1,1

Andersson007,2,1,3,4
acozine,2,1,4,3

markuman,2,4,1,3
jamescassell,2,4,1,3

jillr,1,3,2,4
p-rintz,1,3,2,4
samccann,1,2,4,3
gotmax23,1,1,1,1
KB-perByte,1,1,1,1
alinabuzachis,1,3,2,4
sean-m-sullivan,1,3,2,4
djdanielsson,1,3,2,4
Tompage1994,1,1,1,1
qaxi,1,2,4,3
amott-rh,1,2,-,-
branic,1,3,2,4
NilashishC,1,3,2,4
ivarmu,1,3,2,4
watsonb,1,3,2,4
pyrodie18,1,1,1,1

evanstoner,2,1,-,-

apple4ever,3,1,2,-

sivel,-,-,-,-
bcoca,-,-,-,-
</details>

**Comment by felixfontein** [comment]
Ok, so our counts coincide :-) [According to the rules](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#community-topics-workflow), enough SC members voted (quorum is 6), and option 1 has more than half of the SC votes. So option 1 (JSON-style booleans: `true`/`false`) won.

**Comment by felixfontein** [comment]
PR for adjusting documentation: https://github.com/ansible-community/antsibull-docs/pull/19

**Comment by samccann** [comment]
Issues have been opened for collections so going to close this and thanks everyone for the help!
