### ISSUE TITLE
Removal of officially unmaintained / deprecated collections

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#130]
### Summary

This is a follow-up to #124 

The current process to identify and remove an unmaintained collection looks very much focused on abandoned collections. It takes quite long because we want to make sure that it is really not maintained anymore.

That's OK, but I think we should have a way to remove a collection that announces itself as being unmaintained / deprecated quicker. My suggestion is to remove a collection that announces itself as unmaintained or deprecated **without a vote** from the next major release.

Suggestion: ansible-collections/overview#214

**Comment by felixfontein** [comment]
I would like to clarify what 'next major Ansible version' means exactly. Because if feature freeze for the next one is tomorrow (as an extreme example), I think this should be delayed to the next one. How about: if Ansible X.4.0 has not yet been released, remove from (X+1).0.0. Otherwise, remove from (X+2).0.0. The X.4.0 release is approximately half-way between the X.0.0 and the (X+1).0.0 release.

For this release cycle, that would mean:

6.0.0 release: 2022-06-21
6.4.0 release: 2022-09-20
7.0.0 feature freeze: 2022-11-08
7.0.0 release: 2022-11-29

(we shortened the period between feature freeze and GA, that's why the 6.4.0 release is closer to 7.0.0 than 6.0.0; in future cycles, this should be closer to the middle)

**Comment by mariolenz** [comment]
> I would like to clarify what 'next major Ansible version' means exactly. Because if feature freeze for the next one is tomorrow (as an extreme example), I think this should be delayed to the next one.

Good point :+1: 

However, I think we shouldn't wait until X+2 if we're already on X.5.0. If the collection is deprecated, we should get rid of it as fast as possible.

I think there's one version where downwards incompatibility / breaking changes are problematic... RC1? I'm not sure. But I think it would be OK to remove an officially _unmaintained_ collection up until then.

**Comment by mariolenz** [comment]
I think we can close this since ansible-collections/overview#214 has been merged.
