### ISSUE TITLE
Collection Inclusion: are we satisfied with how things are going?

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-topics#152]
### Summary

**How things are working now:**
- The Ansible community package can be expanded with new collections satisfying the [Collection Requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst). It's the only way for new collections to get in.
- See the [inclusion workflow](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#collection-inclusion-requests-workflow) and the [submission/review process](https://github.com/ansible-collections/ansible-inclusion/blob/main/README.md) for details
- Collection maintainers submit an [inclusion request](https://github.com/ansible-collections/ansible-inclusion/discussions/)
- They wait for, at least,
  a) 2 Steering Committee reviews and approvals OR
  b) 1 Steering Committee + 1 Community review and approvals + 1 additional SC approval (without review)
- We use [Bullhorn](https://github.com/ansible/community/wiki/News#the-bullhorn) to announce requests waiting for reviews but it seems not really working 

**Issues:**
- The main issue at the moment is the lack of interest in reviewing the requests from the community and the Steering Committee [members](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#current-steering-committee-members). For example, currently I review every collection. I don't mind but is this what we really want?
- Maintainers often wait for months to get the first review. Same for the second.

**What was done to improve the situation:**
- Speaking about reviews and approvals mentioned above, there was only option `a` for some time from the beginning. Later we eased this by introducing option `b` but it hasn't helped much.
- We also try to engage submitter to review each other requests. If they do, their requests will be handled with higher priority. We added this point to the [submission process](https://github.com/ansible-collections/ansible-inclusion/blob/main/README.md#submission-process) not a long time ago, so it's hard to say if it gives any positive effect. Nobody has done it so far.
- We are conduction a presentation about inclusion in the Contributor Summit (as it hasn't happened yet, it's impossible to say whether or not it has any positive effect).

**Questions:**
1. Are we happy in general with the inclusion model we use? Should it be anyhow significantly redesigned? Any (even crazy) ideas are welcome.
2. Any ideas on how we can improve the situation, i.e. increase community engagement?

**Collected ideas:**
- Andersson007: add dedicated docs to contributor guidelines on docs.ansible.com (though I doubt it'll change the situation noticeably)
- Andersson007: maybe eliminate the second SC member approval, i.e. to make 1 SC + 1 Community member approval enough?
- Andersson007: regular inclusion review days (we did one advertised via Bullhorn)? How often?
- **<Your idea here, please comment>**

**Comment by mariolenz** [comment]
> The main issue at the moment is the lack of interest in reviewing the requests from the community and the Steering Committee [members](https://docs.ansible.com/ansible/devel/community/steering/community_steering_committee.html#current-steering-committee-members).

In my case it's not so much a lack of interest, it's more a lack of time. I'm maintaining [collection.vmware](https://github.com/ansible-collections/community.vmware) and try to do what I can for the community package, but inclusion reviews consume a lot of time (imho) that I just don't have. I'm doing this in my spare time time ;-)

> For example, currently I review every collection. I don't mind but is this what we really want?

I'm not sure. But I think if you approve an inclusion request, I trust that the collection really is sane :-)

> Maintainers often wait for months to get the first review. Same for the second.

I agree that this is a problem.

> 1. Are we happy in general with the inclusion model we use? Should it be anyhow significantly redesigned? Any (even crazy) ideas are welcome.

As you've said above, the process takes too long because we're lacking reviewers. So I'm not really happy with it.

> 2. Any ideas on how we can improve the situation, i.e. increase community engagement?

Not really. Are there any checks we can automate?

> maybe eliminate the second SC member approval, i.e. to make 1 SC + 1 Community member approval enough?

Maybe even drop the second review? So if one SC member approves, the collection will be included?

At the same time, let's make it easier to remove collections. You know I've put in a lot of work to find and remove unmaintained collections. @gotmax23 worked on finding included collections that [fail the requirement of tagging their releases](https://github.com/ansible-community/community-topics/issues/148), and @dmsimard found out that the majority of the included collections [failed current sanity tests](https://github.com/ansible-community/community-topics/issues/96#issuecomment-1116661339).

I don't like that we make it so hard for collections to be included, while at the same time the collections that are already included are so hard to remove when they fail the requirements. Especially, I dont know why we should wait until Ansible now+2 to remove unmaintained collections.

I'll try to find the time to have a look at the [checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md). IIRC there are some things I always found a bit... well, problematic isn't really the word I'm looking for, but I don't find a better one at the moment.

**Comment by felixfontein** [comment]
> Maybe even drop the second review? So if one SC member approves, the collection will be included?

This is a direction I don't like, I don't think we should compromise on quality. I think we should rather stop including new collections than decreasing the minimum number of reviewers. Even if a reviewer only spends half an hour glancing over the collection, checking for some points they particularly care about, they are likely to find at least something that can be improved and that the other person did miss (obviously not intentionally).

> > 2. Any ideas on how we can improve the situation, i.e. increase community engagement?
> 
> Not really. Are there any checks we can automate?

Some of them definitely can be, while quite a few cannot (or only heuristically).

One thing that could be improved (but not by us) if the submitters actually thouroughly check the checklist and the inclusion document before submitting their collection. For quite a few collections I've reviewed this obviously wasn't done, and could have saved a lot of back and forth (and would have made it a lot easier to review the collection).

**Comment by Andersson007** [comment]
Thank you for your feedback, folks!
When reading it, an idea came to mind that we should explicitly mention `idempotency` in the [requirements](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst) and [checklist](https://github.com/ansible-collections/overview/blob/main/collection_checklist.md).
Ideas? If you're OK with it, I could add it (or please say that you want to do it if you wish)

**Comment by felixfontein** [comment]
Idempotency is already part of the best practices we require (https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_best_practices.html#following-ansible-conventions), but I think it's a good idea to mention that explicitly.

**Comment by Andersson007** [comment]
Created a PR to mention idempotency https://github.com/ansible-collections/overview/pull/220, please take a look (i don't think we should formally vote on it)

**Comment by Andersson007** [comment]
Idempotency is done in https://github.com/ansible-collections/overview/pull/220.
Another idea: How about adding a requirement to have in a collection's README a link to the `news-for-maintainers` repo and that maintainers should subscribe and track it?

**Comment by Andersson007** [comment]
Closing as it seems working, thanks everyone!
