### ISSUE TITLE
Should we assure all ansible modules have valid docs?

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/community-topics#18]
### Summary

I raised this originally at  https://github.com/ansible-collections/community.general/issues/2501#issuecomment-840789181 but I will copy paste important bits here:

While trying to dump documentation (`ansible-doc --json modulename`) for all >5400 Ansible 3.4.0 modules, I discovered that 4 of them are missing documentation:
```
openstack.collect_logs.ara_influxdb.json
openstack.collect_logs.ara_graphite.json
fortinet.fortios.fortios_configuration_fact.json
cisco.intersight.intersight_local_user_policy.json
```

This should not have happened and is dangereus not to test exclisitely for this: that a clean ansible install does contain only modules with documentation, otherwise calling doc command on them will fail. That is easy to script as I already wrote some code that does that for the schemas project.

What we need to determine is which project is suppose to implement these safeguards, later we can even start to be more picky about how complete is the produced doc.

**Comment by gundalow** [comment]
@ssbarnea Yes, they all should do.
Just looking at the last one in the list, the issue is they are not running `ansible-test sanity`, just ran it on their collection locally and there are a lot of issues. 

We will need to raise an issue per repo to get these fixed, and for those using GitHub point them to https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml#L7-L65

**Comment by tadeboro** [comment]
New collections that we include should have the documentation because we require sanity tests to pass. But collections that were grandfathered into the community package were not checked when they were split from the ansible/ansible repository.

So I agree with @gundalow here: we should open bug reports on affected repositories and make sure they run sanity tests. And maybe we should dedicate some time to go over the existing collections that are included in the community package and check them against the rules we have for new inclusion candidates?

**Comment by felixfontein** [comment]
@tadeboro +1 on checking already included collections! Just making sure sanity tests are running (and passing!) and that no "forbidden" entries are in ignore.txt is probably already a good start. I would try to automate as much as possible of these things, since everything that needs to be done manual is PITA :) (This also overlaps with #15.)

**Comment by ssbarnea** [comment]
Closing as it is covered by sanity
