### ISSUE TITLE
Deprecate and finally remove iDRAC modules

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#199]
### Summary

#192 gave me the idea to propose the deprecation and finally the removal of the iDRAC modules. There's the [dellemc.openmanage ](https://github.com/dell/dellemc-openmanage-ansible-modules) collection which is maintained and also part of the community package.

They have some iDRAC related modules, too. It looks like they don't really have drop-in replacements for `idrac_redfish_command`, `idrac_redfish_config` and `idrac_redfish_info` but we could ask them if they would agree to move those modules to their collection in the long run. Or, maybe, this isn't even necessary because they already provide better alternatives.

What do you think?

**Comment by felixfontein** [comment]
The `idrac_redfish_command`, `idrac_redfish_config`, and `idrac_redfish_info` modules landed in community.general because the dellemc.openmanage collection did not want to have them. Other idrac modules were directly moved to dellemc.openmanage during the initial migration (search https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml for `idrac`). Also these modules depend on the redfish module utils in community.general.

Also note that the redfish modules in community.general are actively maintained. One possibility would be moving them to a new collection, say `community.redfish`, but that would depend on whether someone would want to maintain that collection. (Maintaining a collection is more work than maintaining some modules in c.g.)

**Comment by felixfontein** [comment]
CC @mraineri @tomasg2012 @xmadsen @renxulei @rajeevkallur @bhavya06 @mikemoerk @TSKushal

**Comment by mariolenz** [comment]
Damn. And I thought this such a good idea :-(

**Comment by felixfontein** [comment]
Moving the idrac modules to a separate collection could be a good thing. But it needs someone / a group of folks who want to maintain that.

**Comment by mraineri** [comment]
I agree with Felix; I wish we could rely on that other community to push the iDRAC functionality, but the scope and semantics are a bit different. I also don't have the bandwidth to maintain a collection and appreciate the fact that I can leverage the support of the community general collection.

**Comment by mariolenz** [comment]
Since this isn't the brilliant idea I thought it was, it's probably best to close this.
