### ISSUE TITLE
Schedule for Ansible-5.0.0

### ISSUE THREAD

**Issue by abadger** [ansible-community/community-topics#21]
### Summary

Now that Ansible-4 has been released, it's time to nail down the Ansible-5 release schedule.

Here's a draft schedule for discussion:

https://hackmd.io/y7BBcweNR3aRVLuMbKkDxw

**Comment by abadger** [comment]
I've created the ansible-build-data/5/ directory now.  In the schedule, I've made the date to create ansible-build-data/6/ the beta1 date.  That way we never have a time when a new collection review would stall waiting for an ansible-build-data directory to be created.

For changes of existing collections that need to be reflected in ansible.in, beta1/freeze is probably a good date but there is a bit of grey in that.  Here's two examples:
* Removing a collection from the next version of ansible: beta1.  If you can do it even earlier, that would be better.
* Pinning a version because of known incompatibilities with other collections or major bugs: anytime before rc1.  Possibly after rc1 but triggering a new release candidate.  Also okay to submit these to the current release (ie: ansible-4 right now).  These types of changes are generally some sort of bugfix.  They might need to be looked at on a case by case basis but I think the rationale for including them or not should be apparent in most cases.

**Comment by abadger** [comment]
New section on the schedule hackmd.io document for changes to existing collections: https://hackmd.io/y7BBcweNR3aRVLuMbKkDxw#Changes-to-ansible-for-existing-collections

I think that section should probably be moved to the new community docsite once we have that up and running.

**Comment by abadger** [comment]
Yeah, that's a good point.

**Comment by jillr** [comment]
@abadger @felixfontein What would constitute an appropriate warning for the ansible package?  For example if a collection has been announcing the removal (or in our specific case, renaming) for a couple of collection releases in changelogs, blog posts, and the bullhorn is that what we're looking for?  Or is that an additional changelog, porting guide, etc needed specific to the package?

**Comment by felixfontein** [comment]
@jillr this should definitely be announced in the `deprecated_features` section of the collection's changelog, or alternatively Ansible's changelog (https://github.com/ansible-community/ansible-build-data/blob/main/4/changelog.yaml), so that it shows up in the porting guide. (My argument for that would be that the removal of a collection should better be announced in the Ansible changelog directly, since it directly affects Ansible as a set of collections.)

In this case, the collection to be removed is also deprecated itself. How about the following:
1. Declare the collection as deprecated in the Ansible changelog, with removal scheduled for Ansible 7.0.0
2. Version 2.0.0 of community.kubernetes (to be included in Ansible 5.0.0) contains only redirects without a deprecation warning. That way, the collection is essentially empty, but no warnings will be shown if its FQCNs are still used.
3. Version 3.0.0 of community.kubernetes (to be included in Ansible 6.0.0) adds deprecation warnings for all redirects. That way, if people forgot to update their FQCNs, they will get explicit warnings.
4. Ansible 7.0.0 will no longer contain community.kubernetes.

Alternatively, if community.kubernetes 2.0.0 would already contain deprecation warnings next to the redirects, I guess we can shorten the cycle and remove the collection in Ansible 6.0.0.

I'm not sure whether it's a good idea to skip the deprecated redirect step and directly remove the collection from Ansible 5.0.0 without having a mechanism (deprecated redirect) which shows every user that something is happening, even if they do not read changelogs, porting guides, and anything else.

I guess this is something we should discuss at a meeting :)

**Comment by felixfontein** [comment]
At the meeting we agreed to the 5.0.0 schedule.

**Comment by gundalow** [comment]
> I think we should avoid removing a collection without a long advance warning and/or deprecation (i.e. announce/deprecate early in the 4.x.0 cycle if removal is planned for 5.0.0).

@felixfontein @abadger @jillr I wonder if we should "last possible date for removal of collections"

**Comment by jillr** [comment]
@gundalow I don't think we need it for 5.0 since the schedule is approved and I don't think there are any collections other than us on a deprecate/remove cycle yet.  For the 6.0 and beyond it would be a good inclusion though, definitely.

**Comment by tadeboro** [comment]
Closing as Ansible 5.0.0 is out.
