### ISSUE TITLE
Move the dates of Ansible Community Package 7.7.0 and 8.1.0 (ETA on 2023/06/20)

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/community-topics#239]
### Summary

https://docs.ansible.com/ansible/devel/roadmap/COLLECTIONS_8.html
https://mailchi.mp/redhat/the-bullhorn-104

**Comment by cybette** [comment]
it should be 8.1.0 :)

related https://github.com/ansible/ansible/pull/80962

**Comment by mariolenz** [comment]
We've had a discussion about choosing the release dates to couple more tightly to ansible-core: #151

So I think it makes sense to change the release date of Ansible 8.1.0 to 2023-06-20 when the release date of ansible-core 2.15.1 is 2023-06-19.

Does anyone know _why_ the ansible-core 2.15.1 ETA is 2023-06-19? I thought they would release every 4 weeks, which would be the 12th... that's why we chose the 13th. Did they change their release cadence or is this a one-time-thing?

I also think that this should have been discussed _before_ merging ansible/ansible#80962 :-/

**Comment by cybette** [comment]
My bad, I pinged Sandra to merge it when I noticed the change for 2.15.1 core release ETA. I should have opened it up to discussion beforehand.

My apologies, I'll do better next time!

**Comment by samccann** [comment]
Yeah sorry I was fast on the merge on that one. Should have waited.

**Comment by mariolenz** [comment]
@cybette @samccann Well, looks like a lot of people have missed the later ETA for ansible-core 2.15.1. Anyway, ansible/ansible#80962 is only two days old. There wouldn't have much more time to discuss this, anyway.

I'm just not sure what to do now. Let me think... :thinking:

**Comment by gotmax23** [comment]
This is fine with me. I'd like to keep aligning with ansible-core.

**Comment by gotmax23** [comment]
> I also think that this should have been discussed before merging https://github.com/ansible/ansible/pull/80962 :-/

I opened https://github.com/ansible-community/community-topics/issues/240 to discuss moving these docs to a community controlled repo. This miscommunication is not the fault of the ansible/ansible committers but rather of the poor structure.

**Comment by felixfontein** [comment]
I'm fine with keeping the new date (or another date in that week, like 2023/06/22) since ansible-core 2.15.1 is planned for that week as well. I'm still curious why it is five weeks after 2.15.0 instead of four, though... @bcoca wrote on IRC that this might be related to an AAP release, but I have no idea where to find a release schedule for AAP...

**Comment by sivel** [comment]
> I'm still curious why it is five weeks after 2.15.0 instead of four, though

It was due to an initial scheduling conflict with the AAP release, that ended up not being needed once the AAP release was delayed, but we try to make as few changes as possible once we set the date.  To give the productization team time to get everything packaged for release, we agreed to release 1 week early.

Since we maintain a single 4 week release cycle for all releases, the only thing that changed was the GA date, and then we end up with a 5 week gap for 2.15, to re-align on that 4 week cycle.

We ran into a similar problem with 2.13, but we had already announced the release date, so we made an announcement of it's change https://groups.google.com/g/ansible-announce/c/WRnDafO-EDI/

Since this has happened 2 times for our May release, we've started working to remediate this issue going forward, but nothing firm yet.

**Comment by mariolenz** [comment]
I agree with @felixfontein and @gotmax23: Let's keep the new ETA as it is. The date aligns with the next ansible-core release, what we wanted to do.

I'm sure that a vote would certainly be in favor of this, but probably be finished too late. So let's be pragmatic and say it's OK.

**Comment by maxamillion** [comment]
+1

**Comment by acozine** [comment]
+1 to aligning with ansible-core releases, no matter why they are how they are.

**Comment by mariolenz** [comment]
@anweshadas I didn't make it to the community meeting, but I read it up and it looks like there are no objections.

So I thought we should close this as done, but @cybette mentioned that you probably can't make the June 20 and proposed June 22.

Is this correct? If June 20 is OK for you, I think we should close this. If you want to June 22 I understand that that's OK, but I'm not sure if we should close this issue or keep it open until the roadmap has been updated.

**Comment by sivel** [comment]
I didn't think to note this earlier, but due to June 19 being a US Holiday, the ansible-core releases will happen June 20, barring any unforeseen issues.

**Comment by felixfontein** [comment]
So basically 2023-06-20 won't happen anyway. As mentioned in yesterday's community meeting releases have been delayed by 1-2 days for various reasons (including broken CI, waiting for ansible-core releases, personal reasons, ...) in the past multiple times anyway, so 2023-06-22 is fine as well.

**Comment by anweshadas** [comment]
Since the ETA for Ansible 7.7.0 and Ansible 8.1.0, has been discussed in the community meeting and decided to be, on 2023-06-22, I am closing this issue.

**Comment by mariolenz** [comment]
@anweshadas I've created ansible-community/ansible-build-data#248 to deprecate gluster.gluster. Maybe you can merge it before releasing 7.7.0 / 8.1.0. If not, I'll rebase the PR and add the deprecation to 8.2.0.
