### ISSUE TITLE
Repository clean-up spring 2021 edition

### ISSUE THREAD

**Issue by mscherer** [ansible-community/community-topics#25]
### Summary

So, while searching for reference to freenode to remove, I stumbled on a few repositories that should be IMHO archived:

- [ ] https://github.com/ansible/ansible-container-examples This one is marked as deprecated, but not set as readonly.
- [x] https://github.com/ansible/ansible-lockdown this one likely moved to https://github.com/ansible-lockdown, as pointed by gundalow. The url listed redirect to a new website, and this repo predate RHEL 8 release. 
- [ ] https://github.com/ansible/zuul-test-repo not sure if it is still used. I would love to have it at least updated so it doesn't pollute search result on github
- [X] https://github.com/ansible/ansible-azp same as zuul-test-repo. If no longer used, I guess it can be removed. **Archived**
- [X] https://github.com/ansible/ansible-bare Not sure about this one, maybe it can be archived. **deleted by gundalow**
- [ ] https://github.com/ansible/training-content not touched since 7 years
- [ ] https://github.com/ansible/python-social-auth not tested on any non EOL python version, no commit since 2015
- [ ] https://github.com/ansible/ansiconv not touched since years (2014), likely still python 2 code
- [ ] https://github.com/ansible/django-template ansible container example, so likely need to be archived

Then we also have:
- [ ] https://github.com/ansible/azure-testing seems a test repo, should likely be archived
- [ ] https://github.com/ansible/ansible-container-demo ansible-container is deprecated, so this should be archived too
- [ ] https://github.com/ansible/ansible-runner-aio 1 commit, likely can be archived
- [ ] https://github.com/ansible/ansible-runner-zeromq 2 commits
- [ ] https://github.com/ansible/ansible-runner-http 4 commits

**Comment by mariolenz** [comment]
This issue looks stale, so I think we should close it.

@felixfontein @gundalow @mscherer Please re-open it i you think it's a been a wrong decision from me to close it.

**Comment by gundalow** [comment]
Looks like we've got a set of repos we should archive

**Comment by mariolenz** [comment]
@gundalow Nevertheless, this issue looks pretty stale. I've opened a [thread in the forum](https://forum.ansible.com/t/4530) to discuss this in the community meeting. Maybe this helps to see some progress here.

**Comment by gundalow** [comment]
Sounds good. I'll close this and we can move to the Forum.

**Comment by Andersson007** [comment]
@mariolenz and folks, how about closing all the issues here and putting a message in all the topics asking the authors to create corresponding forum topics if the original issues are still relevant?
But i would do it in a small chunks, say, 5-10 a week or so. What do you think? If anyone is happy, please go ahead or i would do it myself (wrote `mysql` instead of `myself` first, haha)

**Comment by mariolenz** [comment]
If we want to move this completely to the forum, I think we need some kind of master thread so we don't loose track. Something like this issue and what I've tried to do in [Possibly unmaintained collections in Ansible 9](https://forum.ansible.com/t/2569). But it should be a wiki post, otherwise we risk not being able to tick of things after some time (see [here](https://forum.ansible.com/t/3868))!

But let's wait a couple of days and see what people say in the community meeting.
