### ISSUE TITLE
[Associated vote ended on 2023-08-29] Unmaintained collection: hpe.nimble

### ISSUE THREAD

**Issue by mariolenz** [ansible-community/community-topics#254]
### Summary

The [hpe.nimble](https://github.com/hpe-storage/nimble-ansible-modules) collection looks unmaintained / abandoned, it has:

- no new commits since December 2021
- no release on Galaxy since version 1.1.4 2 year ago
- no reaction on hpe-storage/nimble-ansible-modules#60
- no reaction on hpe-storage/nimble-ansible-modules#61
- no answer in hpe-storage/nimble-ansible-modules#62

**Comment by mariolenz** [comment]
[The Bullhorn issue #109](https://mailchi.mp/redhat/the-bullhorn-109) 2023-07-14

**Comment by mariolenz** [comment]
@ansible-community/steering-committee Vote happens in #265

**Comment by mariolenz** [comment]
> There was a response to [hpe-storage/nimble-ansible-modules#59](https://github.com/hpe-storage/nimble-ansible-modules/issues/59) earlier this year.

Possibly, but there hasn't been a new release since 2021. And there are two (hpe-storage/nimble-ansible-modules#54 + hpe-storage/nimble-ansible-modules#61) issues about failing sanity tests without any reaction. Looks pretty unmaintained to me :shrug:

**Comment by felixfontein** [comment]
I tried to ping the last two HPE folks who wrote something in the open PRs in https://github.com/hpe-storage/nimble-ansible-modules/issues/62#issuecomment-1678000773 - maybe we'll get a reaction.

**Comment by felixfontein** [comment]
According to https://github.com/hpe-storage/nimble-ansible-modules/issues/62#issuecomment-1678011862 the collection is supported by HPE and it still works, even though it hasn't been touched since December 2021 and there are no resources allocated to it (yet).

So I don't think it's unmaintained, but it does not satisfy our inclusion rules either - tests haven't been run for a long time, the CI workflow only checks up to ansible-core 2.11 (https://github.com/hpe-storage/nimble-ansible-modules/blob/master/.github/workflows/sanity-test.yml#L18), and sanity tests currently fail (though not with something really important AFAICT from the issue).

**Comment by mariolenz** [comment]
I counted votes:

7 x +1 from SC (mariolenz Andersson007 felixfontein markuman russoz briantist gotmax23), no -1 from SC, 1 x undecided (0) from SC (jamescassell)

no votes from community

Can someone from the @ansible-community/steering-committee confirm?

**Comment by Andersson007** [comment]
@mariolenz i confirm your count, thanks!

**Comment by mariolenz** [comment]
In that case the proposal has been accepted and we will announce to remove the collection from Ansible 10.

Thanks all!

**Comment by mariolenz** [comment]
IIRC we've kept issues like this one about collection removal from version X open until X has been released. However, since we've moved discussions to the [forum](https://forum.ansible.com) and the collection has been removed from 10.0.0.a1, I think we should close this even if 10.0.0 hasn't been released yet.

If someone wants to discuss cancelling the removal / re-adding of the collection, please open a topic in the forum.
