### ISSUE TITLE
Meeting time - end of daylight savings

### ISSUE THREAD

**Issue by jillr** [ansible-community/community-topics#48]
### Summary

Daylight savings will end in the places that observe it for only part of the year soon.  Should we:

1) Keep the same time (18:00 UTC)
2) Move the meeting to 19:00 UTC (should make it the same time of day for people who do observe DST)
3) Something else?

If we change, what date should we change on?
2a) October 31 (most of the world)
2b) November 7 (US, Canada)

Any other proposals?

**Comment by acozine** [comment]
I can do 18:00 UTC or 19:00 UTC, since both are in the middle of the day for me. I am happy to change, or not, on whatever date, as long as it's documented (and the bot pings me).

**Comment by cybette** [comment]
Prefer (1), but also ok with (2a)

**Comment by russoz** [comment]
Prefer 2, either 2a or 2b is fine for me

**Comment by dmsimard** [comment]
Could we do a broader survey to gauge if there is interest in moving the meeting earlier than 18 UTC ?
It's generally late for most of EMEA/APAC and we have people that can't attend because of that.

I don't know what the right tool to do that is ? I recall doodle.com but I also remember seeing better options.
