### ISSUE TITLE
Should there be a version 4.10.0 of Ansible after the release of Ansible 5.0.0 ?

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/community-topics#49]
### Summary

Ansible 5 is scheduled to be released on 2021-11-30.

We are currently up to Ansible 4.7.0 (released Oct 13th) and with the pace of a maintenance release every three weeks we will have:
- Ansible 4.8.0 on 2021-11-02
- Ansible 4.9.0 on 2021-11-23
- and then, should we decide in the affirmative, Ansible 4.10.0 on 2021-12-14.

We've so far stopped running maintenance releases after the following major version came out but it may be appropriate or desired by the community to do a release of 4.10.0.

In any case, we would like to announce the last version in advance and need to decide whether that will be 4.9.0 or 4.10.0.

**Comment by samccann** [comment]
FWIW - this has a docs impact. Today, we support docs for /latest/ and /devel/ only.  Once Ansible 5 comes out, Ansible 4 is no longer 'findable' so to speak, since /latest/ becomes Ansible 5. Ansible 4 will still be there, but won't be included in the left-hand version switcher on the docsite. A reader would need to hack the url to replace /latest/ with /4/. 

So part of this decision should be - is that okay, or do we need to add Ansible 4 to the version switcher for 'some period of time TBD' ?

Off  the top of my head, it's doable and shouldn't be significant extra work, but it is something else we need to decide.

**Comment by dmsimard** [comment]
Announced that 4.10.0 will be the last 4.x release in the 4.8.0 release announcement: https://groups.google.com/g/ansible-announce/c/at_Cjdu-gh4

**Comment by dmsimard** [comment]
Also announced that 4.10.0 will be the last 4.x release in the 5.0.0b1 release announcement: https://groups.google.com/g/ansible-announce/c/McUbCQevk-Q
