### ISSUE TITLE
[Associated vote ended on 2023-03-09] Include semantic markup in plugin DOCUMENTATION strings

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#53]
### Summary

Community Ansible documentation wants to add semantic markup within the module/plugin DOCUMENTATION strings. This gives us improved flexibility on how we display this information. 

### Additional Information

**Background**
This started with [a general dissatisfaction](https://github.com/ansible/community/issues/521#issuecomment-739263018) on how some of the module options and parameters are displayed on docs.ansible.com (what is bold, what is italics, monospace, etc) and the inherent inflexibility of our current markup options.

**Primary goal** - To improve the visual aid that helps readers determine what the differences.​
**Secondary goal** - Do this in such a way that we do not have to touch the code in ansible/ansible again if we decide we need to display this information in a different way.
**Solution** - Introduce a light level of semantic markup, where the developer 'marks' the content for what it is (module, value, option, etc) instead of how  it should display (bold, italics, monospace, etc). This leaves the visual aspect to separate code we can update at will.

**Specific changes**
The [community decided](https://github.com/ansible/ansible/issues/75054#issuecomment-866260433) on the following additions:

- O(key) and O(key=value) for option names, with or without values
- V(value) for standalone option values
- E(env_var) for environment variables
- P(FQCN#plugintype) for plugin references

Existing markup macros will remain, including:

- M(FQCN) for module references
- C(code) for other monospace text such as linux commands
- B(bold_text) and I(italic_text) for other words or phrases an author wants to emphasize

These added macros may impact other projects, such as  Galaxy-ng/Automation Hub, ansible-navigator, possibly the vscode plugin, and the [collection_prep script ](https://github.com/ansible-network/collection_prep) used by some collections to generate local rst docs files.

For more complete details and WIP PRs, see https://github.com/ansible/ansible/issues/75054.

**Comment by felixfontein** [comment]
Here's a proposal to extend `O()`, to allow it to a) validate its contents (make sure you reference options that actually exist!) and b) convert them to links (so users can click on them and end up at the documentation of the option that's mentioned).

The following forms of `O(...)` are allowed:
1. `O(name)` or `O(name=value)` for a top-level option `name` of the current plugin/module;
2. `O(name.sub)` or `O(name.sub=value)` for a suboption `sub` of the top-levle option `name` of the current plugin/module; if you have sub-sub-options, use `O(name.sub.subsub)` etc;
3. `O(FQCN#type:name)` or `O(FQCN#type:name=value)` for a top-level option `name` of the plugin/module `FQCN` (f.ex. `ansible.builtin.uri`) of plugin type `type` (one of `module`, `lookup`, ..., `role`);
4. `O(FQCN#type:name.sub.subsub)` or `O(FQCN#type:name.sub.subsub=value)` for a sub-sub-option `subsub` of a sub-option `sub` of a top-level option `name` of the plugin/module `FQCN` (f.ex. `ansible.builtin.uri`) of plugin type `type` (one of `module`, `lookup`, ..., `role`).

This looks complicated, but as opposed to what we currently have, and what's currently proposed, this allows validation and allows to create links. Retrospectively adding validation and links is not really possible if we allow the free-form version of `O(...)`.

**Comment by felixfontein** [comment]
With that I'd also like to propose a markup for *return values*. Similar as `O(...)` for options, this can be used for stricter validation and linking. Basically I suggest to use `RV(name)` or `RV(name=value)`, with the same adjustments for sub-return values and return values of other modules/plugins as for `O(...)` above. So the generic form will be `RV(FQCN#type:name.sub.subsub=value)`. (For facts, one can simply use `RV(FQCN#type:ansible_facts.name.sub.subsub)`.)

**Comment by felixfontein** [comment]
It probably makes sense to allow to leave away FQCN and plugin type in `O()` and `R()` if they refer to the current plugin/module. This still allows to do proper linking and proper validation, and covers the huge majorities of usages of these markups.

**Comment by samccann** [comment]
Included the above details into a specification at  https://hackmd.io/VjN60QSoRSSeRfvGmOH1lQ

We can use that hackmd doc to finalize our proposed specification and then get it approved by the other projects that depend on this `ansible-doc --json` output.

**Comment by felixfontein** [comment]
Another improvement I'd like to suggest: Allow to escape `)` and `\` by using `\` in values, i.e. in the parts after `=` for `O()` and `RV()`, and in the whole of `V()`. Then it will be possible to include `)`, which right now is *not possible* with `C()`, `I()` and `B()`.

(I would not allow this for `C()`, `I()` and `B()`, since this would be a breaking change in case someone is using something like `C(\)`, which right now is a valid markup for generating `)`, but with this change would generate `)` followed by more code-style content until the next `)` in the input.)

**Comment by felixfontein** [comment]
I've continued on the implementation side of this:
- https://github.com/ansible-community/antsibull/pull/281 now supports all forms of `O()` and `RV()`;
- https://github.com/ansible-collections/community.dns/pull/23 uses this;
- https://github.com/ansible/ansible/pull/74937 supports this markup in ansible-doc output, and adds `ansible-test validate-modules` support both for generic syntax, and for making sure that local option names and return value names mentioned by semantic markup actually exist.

This includes another extension: allowing to use `[]` in option and return value names; see https://github.com/ansible-community/antsibull/pull/281#issuecomment-1000769798 for details. (You can use it for things like `records[].value` to reference the suboption `value` inside the list `records`.)

**Comment by felixfontein** [comment]
I updated the proposal https://hackmd.io/VjN60QSoRSSeRfvGmOH1lQ to include `[]`.

**Comment by samccann** [comment]
A note to say this is on hold until related projects can scope the impact and provide support for this feature.

**Comment by felixfontein** [comment]
Ok, this basically has been blocked for a long time without the community really knowing where this is blocked RH-internally. Apparently changes to documentation must be coordinated with all projects that show documentation, but it is not clear which ones these are (I would guess galaxy_ng/AH, ansible-navigator, maybe the VScode plugin, maybe some more?) - next to ansible-core (ansible-doc in particular) and antsibull-docs, that is. (Form what I've seen so far ansible-navigator does not apply any formatting, so it won't need changes. galaxy_ng/AH does, and after a looong time I finally figured out a few months ago where code lives that does the rendering: https://github.com/ansible/ansible-hub-ui/blob/master/src/components/render-plugin-doc/render-plugin-doc.tsx#L280-L299)

To kind of break this blockage, I propose to simply merge the PRs for antsibull-docs so that we can start using semantic markup in community collections to improve docs.ansible.com/ansible/. As long as the PR for ansible-core isn't merged (no idea whether we can get that done, due to the above), but my hope would be that showing how great semantic markup is by demonstrating it on docs.ansible.com/ansible/ would increase pressure to implement support for it in other places that render documentation.

What do you think, especially members of @ansible-community/steering-committee?

**Comment by briantist** [comment]
It sounds good to me, if we make progress on our own let's do so, it's been too long with no movement and unclear next steps.

**Comment by russoz** [comment]
Makes sense to me.

**Comment by felixfontein** [comment]
**There is an active vote on this topic in #205**

CC @ansible-community/steering-committee

**Comment by felixfontein** [comment]
On IRC the question came up what happens when a user looks at documentation for a collection using semantic markup with a version of ansible-core that does not support semantic markup (or with another tool that doesn't support it).

Basically you will see the raw markup. For example, you would see

> Use O(foo=bar) to set O(foo) to V(var).

Instead of

> Use `foo=bar` to set `foo` to `var`.

**Comment by felixfontein** [comment]
The doc tools that interpret markup (instead of just showing it, like ansible-navigator seems to do) I know of are **antsibull-docs** (for the official docsite, [repo](https://github.com/ansible-community/antsibull-docs/)), **ansible-doc** (part of ansible-core), **galaxy_ng** ([ui part](https://github.com/ansible/ansible-hub-ui/)), **collection_prep** ([repo](https://github.com/ansible-network/collection_prep)), and **ansible-doc-extractor** ([repo](https://github.com/xlab-steampunk/ansible-doc-extractor)). If anyone is aware of more projects/tools, please mention them here.

**Comment by ssbarnea** [comment]
While I do fully agree with the stated problem and that we need to address it, I am (personally) inclined to avoid creating a new markup format for addressing this.

This would not only need building tools to parse it and convert it to other formats like plain markdown or HTML but also linting tools for validating it.

Can we avoid reinventing the wheel and use a JSON Schema based approach for documentation too? That would make it much easier to make it machine friendly. That is also directly linked to how args are defined too, as JSON Schema might be the best way to describe them.

We already have lots of industry tools for building documentation 
(text) from JSON Schemas.

Another tool that is using output of ansible-doc is [ansible-language-server](https://github.com/ansible/ansible-language-server) which uses it to validate the data, provide auto-complete and display documentation. That is a TypeScript project so I am not really keen on implementing and maintaining two parsers/convertors for our **custom "semantic-markup"**, mainly because looks like a [NIH syndrome](https://en.wikipedia.org/wiki/Not_invented_here).

**Comment by felixfontein** [comment]
1) semantic markup is not a new markup, it's an extension to the existing custom Ansible documentation markup. And as opposed to replacing that markup by something else, extending it is actually feasible.
2) General MarkDown or HTML are not good candidates for human-written module/plugin documentation markup IMO: HTML is not so easy to write for humans, and MarkDown is not flexible enough. RST (or a subset of it) would be flexible enough (with roles), but I don't think anyone wants to write a RST parser resp. adjust an existing one to only handle the subset we need / should use.
3) Both ansible-hub-ui and ansible-language-server are JS/TS projects that apply formatting, so in a perfect world there would be one shared JS/TS library which does the processing, and both projects use it. I'm happy to create such a library if both projects want to use it.
4) As mentioned on IRC, I don't see what JSON schemas have to do with semantic markup.

**Comment by mariolenz** [comment]
I counted votes:

9 x +1 from SC (felixfontein briantist gotmax23 Andersson007 mariolenz acozine markuman russoz gundalow)

6 x +1 from community (oraNod tremble cybette sammcann jamescassell bluikko)

Can someone from the Steering Committee confirm?

**Comment by felixfontein** [comment]
@mariolenz I got slightly different numbers, since @jamescassell is part of the SC as well (it's a bit confusing since his IRC nick differs from his GH nick). I got:

- 10 x +1 from SC (felixfontein briantist gotmax23 Andersson007 mariolenz acozine markuman russoz jamescassell gundalow)
- 5 x +1 from community (oraNod tremble cybette samccann bluikko)
- no -1 or 0

So the proposal has been accepted! :tada:

**Comment by felixfontein** [comment]
I've just merged https://github.com/ansible-community/antsibull-docs/pull/4.

**Comment by felixfontein** [comment]
https://github.com/ansible/ansible/pull/74937 is rebased and ready for review.

**Comment by felixfontein** [comment]
[antsibull-docs 1.10.0](https://github.com/ansible-community/antsibull-docs/blob/main/CHANGELOG.rst#v1-10-0) has been released with semantic markup support :tada:

https://github.com/ansible/ansible/pull/80201 makes ansible-core's internal docs build sanity test and the docsite build use it.

**Comment by mariolenz** [comment]
@felixfontein Since both the discussion and the vote are over, can we close this? Or do you prefer to wait until ansible/ansible#80201 is merged?

**Comment by felixfontein** [comment]
@mariolenz as long as the `being_implemented` label is there and accurate, this should stay open. There is a lot of work to be done until this can be closed.

**Comment by mariolenz** [comment]
@felixfontein Sure, no problem. Just wanted to ask ;-)

**Comment by felixfontein** [comment]
https://github.com/ansible/ansible/pull/80201 and https://github.com/ansible/ansible/pull/80242 have been merged. This means that on the devel branch, ansible-core now supports semantic markup for ansible-doc text output, and that the devel Ansible docsite now supports semantic markup as well. If nothing happens, this will also apply for ansible-core 2.15's ansible-doc and the Ansible 7 docsite.

What's missing are two (three) PRs:
- https://github.com/ansible/ansible/pull/80212 prints plugin see-also in ansible-doc's text output
- https://github.com/ansible/ansible/pull/80244 makes validate-modules complain when plugin see-alsos are used
- https://github.com/ansible/ansible/pull/80243 includes https://github.com/ansible/ansible/pull/80244 and also adds some validation of semantic markup (like checking option/return value names in `O()`, `RV()`)

I hope that at least the first two will make it into ansible-core 2.15.0 as well; the third apparently doesn't have much chances for that.

**Comment by felixfontein** [comment]
If anyone has time, some eyes on this would be appreciated! I wanted to add semantic markup to a collection of mine with roles, and noticed that the semantic markup spec doesn't accomodate roles yet - they have entrypoints, so you cannot just refer to a role's option by the role's FQCN and 'role' type, but you also need to provide the entrypoint. I'm proposing a small extension to the `O()` and `RV()` syntax to accomodate entrypoints for roles.

Please take a look: https://github.com/ansible-community/antsibull-docs/pull/113
Example PR for role based collection: https://github.com/felixfontein/ansible-acme/pull/50
Example generated documentation:
- https://ansible.fontein.de/_felixfontein.acme/revoke_old_certificates_role.html#entry-point-main-revoke-old-certificates
- https://ansible.fontein.de/_felixfontein.acme/acme_certificate_role.html#entry-point-main-issue-tls-ssl-certificates-from-an-acme-ca

(Watch out for the links to option names and other roles.)

**Comment by felixfontein** [comment]
ansible-doc implementation for that proposal: https://github.com/ansible/ansible/pull/80305

**Comment by felixfontein** [comment]
https://github.com/ansible-community/antsibull-docs-parser/pull/9 and https://github.com/ansible-community/antsibull-docs-ts/pull/31 implement the specifications for the parser libraries.

**Comment by samccann** [comment]
Positively giddy to be able to mark this one as basically done at this point!! Thanks @felixfontein and everyone who made this happen!

**Comment by felixfontein** [comment]
Re-opening since this is far from being fully implemented.

**Comment by felixfontein** [comment]
PRs for other docs processors:
- collection_prep: https://github.com/ansible-network/collection_prep/pull/88
- ansible-doc-extractor: https://github.com/xlab-steampunk/ansible-doc-extractor/pull/28

**Comment by felixfontein** [comment]
PR for ansible-language-server: https://github.com/ansible/ansible-language-server/pull/563

**Comment by felixfontein** [comment]
PR for ansible-hub-ui: https://github.com/ansible/ansible-hub-ui/pull/3607

**Comment by felixfontein** [comment]
I enabled semantic markup for community.general 7.1.0; the first actual use of semantic markup in community.general will be https://github.com/ansible-collections/community.general/pull/6544 for a case where classic Ansible markup doesn't work.

**Comment by felixfontein** [comment]
The ansible-hub-ui PR has been merged, as has been a backport to stable-4.7 (https://github.com/ansible/ansible-hub-ui/pull/3754). :tada:

**Comment by felixfontein** [comment]
The Ansible language server PR has also been merged; once that repo had a new release, vscode-ansible needs an update (https://github.com/ansible/vscode-ansible/pull/933) to use it.

**Comment by felixfontein** [comment]
ansible-doc-extractor 0.1.10 has been released with semantic markup support!

**Comment by felixfontein** [comment]
ansible-language-server 1.2.0 has been released with semantic markup support!

**Comment by felixfontein** [comment]
All relevant tools support semantic markup; antsibull-doc's collection docs linter checks option and return value names even cross-collections; and some community collections have been using semantic markup for some time. So let's finally close this :tada:
