### ISSUE TITLE
[Vote ended on 2022-01-18] Should documentation use FQCN for ansible.builtin modules or just the short name

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-topics#58]
### Summary

At this point we are inconsistent in our documentation. Some built in modules use FQCN in examples, some do not. See https://github.com/ansible/ansible/pull/73546 for some details.

The general feeling on each side seems to be:

Using FQCN everywhere - is consistent with collections and is a hard guarantee that a user can never have unexpected playbooks results based on some other included collection reusing the short name of a built in module (if used with the `collections:` keyword)

Using shortname for built in modules - makes it clearer that FQCN is not required and also removes some confusion where users will see FQCN for builtin modules and think they need to update their playbooks accordingly.

There are more details in that PR that I'm likely not capturing here yet, so please read over that before we vote.

Docs should be consistent so let's make the final decision here and move on ;-)

**Comment by briantist** [comment]
I don't have a clear opinion on this yet, but if we don't already, we should have a separate page explaining when/why to use short name vs. FQCN and `ansible.builtin` vs `ansible.legacy`.

**Comment by felixfontein** [comment]
Using FQCN in examples makes it easier to copy them, since whether they work does not depend on what you have in a local `library/` folder or listed in the `collections:` keyword.

**Comment by samccann** [comment]
@briantist see https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#simplifying-module-names-with-the-collections-keyword for what we have today.
As for `ansible.legacy` I didn't even know it was 'a thing' until digging into the comments on that linked in PR.  This is all I could find in the docs for this https://docs.ansible.com/ansible/latest/dev_guide/migrating_roles.html#using-ansible-legacy-to-access-local-custom-modules-from-collections-based-roles

**Comment by tadeboro** [comment]
I have been an advocate for "only use FQCNs" since forever. The main reason behind my conviction is consistency, and that one is closely followed by the "I wish `collections` keyword were not a thing.

Of course, in the real world, things are a bit more complicated because 2.9 is still alive and kicking. So my current advice to our customers is usually:

 1. If you can use Ansible >= 2.10.0, only use FQCNs.
 2. If you are stuck with Ansible 2.9, use short names if you only use content from the all-in-one package. If you use collections with Ansible 2.9, use FQCNs and manually install collections that you need even if the module is part of Ansible 2.9.

But since the latest docs do not have to be concerned with Ansible 2.9 at this point, I would say we can get away with always using FQCNs.

As for `ansible.legacy`, I am not sure how much we want to talk about it. As far as I can understand, this synthetic collection is only there to make gradual role migration into collections possible. But even in this case, I would suggest users to do the migration in a different way: they should first move their local modules into collections, update roles to use FQCNs for those new collections, and then move roles into their final destination. This way, the legacy collection is not needed.

**Comment by jrglynn2** [comment]
I agree with @tadeboro ... always use FQCNs

**Comment by jillr** [comment]
Agreed with only use FQCNs to keep the documentation consistent

**Comment by Andersson007** [comment]
FQCN everywhere (at least for doc consistency) sounds good to me

**Comment by sivel** [comment]
@thaumos should probably weigh in here.  AFAIK we are telling customers they must use FQCN everywhere, and as such, docs probably should too.

I don't really agree with docs using ansible.builtin, but at this point I think that ship has sailed.

**Comment by acozine** [comment]
+1 for FQCN everywhere.

**Comment by Andersson007** [comment]
Let's establish a vote end date. How about `18 Jan 2022`? If no objections, I'll change the topic's description tomorrow.

**Comment by xenlo** [comment]
Since we moved to Ansible 2.10 in our projects (Feb 2021) we enforced the usage of the FQCN by adding a rule about it in our 'Coding Guidelines'.

So definitively +1 for FQCN everywhere.

**Comment by Andersson007** [comment]
**IMPORTANT**: vote ends at `18 Jan 2022`, so please vote who haven't done it yet.

**Comment by gundalow** [comment]
+1 for FQCN everywhere.

**Comment by thaumos** [comment]
+1

**Comment by cybette** [comment]
+1 for consistency of FQCN everywhere

**Comment by sean-m-sullivan** [comment]
The ONLY reason I have seen to NOT use FQDN's is if your making a role flexible to use either awx.awx, ansible.tower, or ansible.controller, which are the same modules in different forms. For Documentation yes, FQDN everywhere, But advocate for leaving it as optional but strongly/highly encouraged in code. 
+1

**Comment by maxamillion** [comment]
+1 for consistency of FQCN anywhere possible

**Comment by cidrblock** [comment]
post vote close, but +1 :)

**Comment by briantist** [comment]
+1 (I think I forgot to actually vote after commenting)

**Comment by jillr** [comment]
Second count:
SC: +8
Community+ +6

**Comment by samccann** [comment]
Being implemented by https://github.com/ansible/ansible/pull/73546

**Comment by samccann** [comment]
Resolved by https://github.com/ansible/ansible/pull/73546
